// src/routes/moneypulse/Footer.svelte
<footer class="white-section" id="footer">
	<div class="container-fluid">
		<!-- svelte-ignore a11y_consider_explicit_label -->
		<a href="https://www.twitter.com/jeffryhermanto/" target="_blank">
			<i class="social-icon fa-brands fa-x-twitter"></i>
		</a>

		<!-- svelte-ignore a11y_consider_explicit_label -->
		<a href="https://www.instagram.com/jeffryhermanto/" target="_blank">
			<i class="social-icon fa-brands fa-instagram"></i>
		</a>

		<!-- svelte-ignore a11y_consider_explicit_label -->
		<a href="https://www.tiktok.com/@jeffry.hermanto/" target="_blank">
			<i class="social-icon fa-brands fa-tiktok"></i>
		</a>

		<p>© 2025 Jeffry Hermanto. All rights reserved.</p>
	</div>
</footer>

// components/Footer.vue
<template>
  <!-- Start Footer -->
  <footer class="footer-area sky-blue">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12">
          <div class="footer-top flex-column">
            <div class="footer-logo text-center">
              <a href="#">
                <img src="assets/img//logo.png" alt="logo" />
              </a>
              <h4>Follow Me</h4>
            </div>
            <div class="footer-social text-center">
              <a href="https://github.com/jeffryhermanto" target="_blank">
                <i class="fa fa-github transition"></i>
              </a>
              <a href="https://linkedin.com/in/jeffryhermanto" target="_blank">
                <i class="fa fa-linkedin transition"></i>
              </a>
              <a href="https://instagram.com/jeffryhermanto" target="_blank">
                <i class="fa fa-instagram transition"></i>
              </a>
              <a href="https://twitter.com/jeffryhermanto" target="_blank">
                <i class="fa fa-twitter transition"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="row footer-bottom text-center justify-content-center">
        <p class="col-lg-8 col-sm-12 footer-text">
          Copyright © All rights reserved | Made with
          <i class="fa fa-heart-o" aria-hidden="true"></i> by
          <a href="https://www.jeffryhermanto.com">Jeffry Hermanto</a>
        </p>
      </div>
    </div>
  </footer>
  <!-- End Footer -->
</template>
<script>
export default {
  name: "Footer"
};
</script>
